version: '3.9'

services:
  elasticsearch:
    container_name: es_elasticsearch
    build: es
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/data/:/usr/share/elasticsearch/data/
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./es/logs/:/usr/share/elasticsearch/logs
      - ./es/repo/:/mount/backups
    environment:
      #(Static) Specifies whether Elasticsearch should form a multiple-node cluster. Defaults to multi-node
      #- "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - xpack.security.enabled=false
      - xpack.graph.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - test_esnet

  mysql:
    container_name: mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=256M
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      # Data initialize script trigger directory. place initialize file under the mysql_init directory.
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # persistent data directory
      - ./db/mysql_data:/var/lib/mysql
      # configuration file
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    networks:
      - test_esnet

networks:
  test_esnet: